# Generated by Django 4.2.1 on 2023-05-04 18:57

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('release_year', models.IntegerField()),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None)),
                ('picture', models.ImageField(upload_to='album_images')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('followers', models.IntegerField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='artist_pictures/profile_pictures/')),
                ('banner_pic', models.ImageField(blank=True, null=True, upload_to='artist_pictures/banner_pictures/')),
                ('is_verified', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('playlist_image', models.ImageField(blank=True, null=True, upload_to='playlist_images/')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('length', models.IntegerField()),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('lyrics', models.TextField()),
                ('media_mp3', models.FileField(upload_to='songs/')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.album')),
                ('artists', models.ManyToManyField(to='backend_api.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=500)),
                ('display_name', models.CharField(max_length=500)),
                ('isPremium', models.BooleanField()),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('artists', models.ManyToManyField(to='backend_api.artist')),
                ('playlists', models.ManyToManyField(to='backend_api.playlist')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='backend_api.song'),
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(to='backend_api.artist'),
        ),
    ]
