# Generated by Django 4.2.1 on 2023-05-03 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='../media/profile_pictures/'),
            preserve_default=False,
        ),
    ]
