# Generated by Django 4.2.1 on 2023-05-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='is_verified',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
