# Generated by Django 4.2.1 on 2023-05-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_artists_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField()),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Artists',
        ),
        migrations.AddField(
            model_name='profile',
            name='artists',
            field=models.ManyToManyField(to='backend_api.artist'),
        ),
    ]
