# Generated by Django 4.2.1 on 2023-05-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_song'),
        ('backend_api', '0010_artist_banner_pic_artist_followers_and_more'),
    ]

    operations = [
    ]
