# Generated by Django 4.2.1 on 2023-05-04 17:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0011_merge_20230503_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('release_year', models.IntegerField()),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None)),
                ('picture', models.ImageField(upload_to='album_images')),
            ],
        ),
        migrations.AlterField(
            model_name='artist',
            name='banner_pic',
            field=models.ImageField(blank=True, null=True, upload_to='artist_pictures/banner_pictures/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='artist_pictures/profile_pictures/'),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('playlist_image', models.ImageField(blank=True, null=True, upload_to='playlist_images/')),
                ('description', models.CharField(max_length=300)),
                ('songs', models.ManyToManyField(to='backend_api.song')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='playlists',
            field=models.ManyToManyField(to='backend_api.playlist'),
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.album'),
        ),
    ]
