# Generated by Django 4.2.1 on 2023-05-03 21:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0011_merge_20230503_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(to='backend_api.artist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='banner_pic',
            field=models.ImageField(blank=True, null=True, upload_to='artist_pictures/banner_pictures/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='artist_pictures/profile_pictures/'),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('playlist_image', models.ImageField(blank=True, null=True, upload_to='playlist_images/')),
                ('description', models.CharField(max_length=1000)),
                ('songs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.song')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='playlists',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='backend_api.playlist'),
            preserve_default=False,
        ),
    ]
