# Generated by Django 4.2.1 on 2023-05-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0012_album_song_artists_alter_artist_banner_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(to='backend_api.artist'),
        ),
    ]
